version: '3'
services:
  app:
    container_name: tolgee_e2e
    image: tolgee/tolgee:local
    ports:
      - 8201:8201
      - 8091:8091
    environment:
      - spring.profiles.active=docker,e2e,${SPRING_PROFILES_ACTIVE:-default}
      - tolgee.smtp.host=fakesmtp
      - tolgee.smtp.port=1025
      - tolgee.frontend-url=http://localhost:8201
      # tests go brrrr but then get 429'd and no longer go brrrr
      - tolgee.rate-limits.enabled=false
  fakesmtp:
    image: reachfive/fake-smtp-server:0.8.1
    ports:
      - "21025:1025"
      - "21080:1080"
  cockroachdb:
    container_name: tolgee_cockroach_e2e
    image: cockroachdb/cockroach:v22.1.9
    ports:
      - 26257:26257
    command:
      - start-single-node
      - --insecure
volumes:
  e2e-db-data:
